/**
 * Storage abstraction for request attachments. The HTTP layer never sees
 * the underlying bytes-backend (local FS, S3, Azure Blob, …) — it only
 * deals with opaque storage keys.
 *
 * Implementations MUST treat `storageKey` as opaque: it is generated by
 * the adapter on `put` and persisted in the database alongside the
 * metadata. The adapter is then queried by key for `get` and `delete`.
 */
export interface StorageAdapter {
  /**
   * Persist a file's bytes. Returns the opaque storage key the adapter
   * has chosen — typically a UUID, possibly prefixed with `requestId/`
   * for human-friendly directory grouping.
   */
  put(input: PutInput): Promise<{ storageKey: string }>;

  /** Stream the file back. Throws if the key is unknown. */
  get(storageKey: string): Promise<NodeJS.ReadableStream>;

  /** Remove the file. Must be idempotent — deleting an unknown key is a no-op. */
  delete(storageKey: string): Promise<void>;
}

export interface PutInput {
  /** Which request this file belongs to — used for directory grouping. */
  requestId: string;
  /** User-supplied filename, NOT trusted as a storage path. */
  fileName: string;
  /** Bytes to write. */
  data: Buffer;
}

export const STORAGE_ADAPTER = Symbol('STORAGE_ADAPTER');
