/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['AuthController_login'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['AuthController_refresh'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['AuthController_me'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/me/preferences': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations['AuthController_updatePreferences'];
    trace?: never;
  };
  '/api/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['HealthController_check'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/employees': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['EmployeesController_list'];
    put?: never;
    post: operations['EmployeesController_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/employees/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['EmployeesController_get'];
    put: operations['EmployeesController_update'];
    post?: never;
    delete: operations['EmployeesController_deactivate'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/employees/{id}/password': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['EmployeesController_setPassword'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/employees/{id}/reactivate': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['EmployeesController_reactivate'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/work-schedules': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['WorkSchedulesController_list'];
    put?: never;
    post: operations['WorkSchedulesController_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/work-schedules/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['WorkSchedulesController_get'];
    put: operations['WorkSchedulesController_update'];
    post?: never;
    delete: operations['WorkSchedulesController_remove'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/work-schedules/{id}/assign': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['WorkSchedulesController_assign'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/work-schedules/{id}/bulk-assign': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['WorkSchedulesController_bulkAssign'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/projects': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['ProjectsController_list'];
    put?: never;
    post: operations['ProjectsController_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/projects/assignments': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['ProjectsController_listAssignments'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/projects/bookable': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['ProjectsController_listBookable'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/projects/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['ProjectsController_get'];
    put: operations['ProjectsController_update'];
    post?: never;
    delete: operations['ProjectsController_remove'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/projects/{id}/report': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['ProjectsController_report'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/projects/{id}/service-orders': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['ProjectsController_createServiceOrder'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/projects/{id}/service-orders/{orderId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: operations['ProjectsController_updateServiceOrder'];
    post?: never;
    delete: operations['ProjectsController_removeServiceOrder'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/projects/{id}/assignments/{employeeId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: operations['ProjectsController_assign'];
    post?: never;
    delete: operations['ProjectsController_unassign'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/reports/working-times/employees': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['ReportsController_workingTimeEmployees'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/reports/working-times': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['ReportsController_workingTimes'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/timeentries': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['TimeEntriesController_list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/timeentries/clock-in': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['TimeEntriesController_clockIn'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/timeentries/clock-out': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['TimeEntriesController_clockOut'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/timeentries/daily-block/option': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['TimeEntriesController_dailyBlockOption'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/timeentries/daily-block': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['TimeEntriesController_dailyBlock'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/timeentries/book-project': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['TimeEntriesController_bookProject'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/timeentries/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations['TimeEntriesController_update'];
    trace?: never;
  };
  '/api/timeentries/{id}/split': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['TimeEntriesController_split'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/terminals/support-prompt': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['TerminalsController_supportPrompt'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/terminals/support-prompt/dismiss': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['TerminalsController_dismissSupportPrompt'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/terminals/pair': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['TerminalsController_pair'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/terminals/kiosk': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['TerminalsController_kiosk'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/terminals/scan': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['TerminalsController_scan'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/terminals': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['TerminalsController_list'];
    put?: never;
    post: operations['TerminalsController_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/terminals/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['TerminalsController_get'];
    put: operations['TerminalsController_update'];
    post?: never;
    delete: operations['TerminalsController_deactivate'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/terminals/{id}/permanent': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations['TerminalsController_deletePermanently'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/terminals/{id}/pairing': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['TerminalsController_createPairing'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/terminals/{id}/devices/{deviceId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations['TerminalsController_revokeDevice'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/employees/{employeeId}/leave-allowances': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['LeaveAllowancesController_list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/employees/{employeeId}/leave-allowances/{year}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: operations['LeaveAllowancesController_upsert'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/leave-allowances/expire-carryovers': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['LeaveAllowancesAdminController_expireCarryOvers'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/cron/expire-carryovers': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['CronCarryOverController_expireCarryOvers'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/accounts/{employeeId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['AccountsController_account'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/accounts/{employeeId}/vacation': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['AccountsController_vacationBalance'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/requests': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['RequestsController_list'];
    put?: never;
    post: operations['RequestsController_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/requests/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['RequestsController_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/requests/{id}/events': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['RequestsController_events'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/requests/vacation': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['RequestsController_createVacation'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/requests/{id}/approve': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['RequestsController_approve'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/requests/{id}/reject': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['RequestsController_reject'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/requests/{id}/manager-approve': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['RequestsController_managerApprove'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/requests/{id}/manager-reject': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['RequestsController_managerReject'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/requests/{id}/hr-confirm': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['RequestsController_hrConfirm'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/requests/{id}/hr-reject': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['RequestsController_hrReject'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/requests/{id}/substitute/accept': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['RequestsController_substituteAccept'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/requests/{id}/substitute/decline': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['RequestsController_substituteDecline'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/requests/{id}/return': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['RequestsController_returnForRevision'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/requests/{id}/cancel': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['RequestsController_cancel'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/requests/bulk-approve': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['RequestsController_bulkApprove'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/requests/bulk-reject': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['RequestsController_bulkReject'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/absences': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['AbsencesController_list'];
    put?: never;
    post: operations['AbsencesController_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/absences/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: operations['AbsencesController_update'];
    post?: never;
    delete: operations['AbsencesController_remove'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/requests/{requestId}/attachments': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['AttachmentsController_list'];
    put?: never;
    post: operations['AttachmentsController_upload'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/attachments/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['AttachmentsController_download'];
    put?: never;
    post?: never;
    delete: operations['AttachmentsController_remove'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/violations': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['ViolationsController_list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/erp/timeentries': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['ErpExportController_list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    LoginDto: {
      /** @example hannah.roth@openclockwork.test */
      email: string;
      /** @example openclockwork */
      password: string;
    };
    RefreshDto: {
      /** @description A refresh token previously returned from /auth/login or /auth/refresh. */
      refreshToken: string;
    };
    /**
     * @description Light / Dark / System. System follows the OS color-scheme media query in the browser.
     * @enum {string}
     */
    ThemePreference: 'Light' | 'Dark' | 'System';
    UpdatePreferencesDto: {
      /** @description Light / Dark / System. System follows the OS color-scheme media query in the browser. */
      themePreference: components['schemas']['ThemePreference'];
    };
    HealthResponseDto: {
      /** @example ok */
      status: string;
      /** @example openclockwork-api */
      service: string;
      /** @example 1.4.0 */
      version: string;
      /** Format: date-time */
      utcTimestamp: string;
    };
    CreateEmployeeDto: {
      /** @example 1001 */
      personalNo: string;
      /** @example Anna */
      firstName: string;
      /** @example Mueller */
      lastName: string;
      /** @example anna.mueller@openclockwork.test */
      email: string;
      /** @description Initial password — bcrypt-hashed on the server. */
      password: string;
      /**
       * @example Employee
       * @enum {string}
       */
      role: 'Employee' | 'Manager' | 'HRAdmin';
      /**
       * @example Vollzeit
       * @enum {string}
       */
      timeModel:
        | 'Teilzeit'
        | 'Vollzeit'
        | 'Vertrauensarbeitszeit'
        | 'Gleitzeit';
      /** @example 40 */
      weeklyHours: number;
      /** @example 30 */
      annualLeaveDays: number;
      /**
       * @description ISO date when the employee starts; target working hours are counted from here.
       * @example 2026-04-01
       */
      startDate: string;
      /**
       * @description One-time overtime carry-over in minutes (signed).
       * @example 0
       */
      overtimeOpeningBalanceMinutes?: number;
      /**
       * @deprecated
       * @description Legacy alias for a DE-XX holidayCalendar; use holidayCalendar for new clients.
       * @enum {string}
       */
      bundesland?:
        | 'BW'
        | 'BY'
        | 'BE'
        | 'BB'
        | 'HB'
        | 'HH'
        | 'HE'
        | 'MV'
        | 'NI'
        | 'NW'
        | 'RP'
        | 'SL'
        | 'SN'
        | 'ST'
        | 'SH'
        | 'TH';
      /**
       * @description Optional holiday preset. NONE makes no public-holiday assumptions; explicit holidayDates work in every country.
       * @default NONE
       * @enum {string}
       */
      holidayCalendar:
        | 'NONE'
        | 'DE-BW'
        | 'DE-BY'
        | 'DE-BE'
        | 'DE-BB'
        | 'DE-HB'
        | 'DE-HH'
        | 'DE-HE'
        | 'DE-MV'
        | 'DE-NI'
        | 'DE-NW'
        | 'DE-RP'
        | 'DE-SL'
        | 'DE-SN'
        | 'DE-ST'
        | 'DE-SH'
        | 'DE-TH';
      /**
       * @description Explicit non-working dates in YYYY-MM-DD format; supplement the selected preset.
       * @example [
       *       "2026-07-01"
       *     ]
       */
      holidayDates?: string[];
      /**
       * @description Allow one self-approved fixed-duration block on a configured working day.
       * @default false
       */
      allowDailyBlockBooking: boolean;
      /** Format: uuid */
      managerId?: Record<string, never> | null;
      /** Format: uuid */
      workScheduleId?: Record<string, never> | null;
    };
    UpdateEmployeeDto: {
      personalNo?: string;
      firstName?: string;
      lastName?: string;
      email?: string;
      /** @enum {string} */
      role?: 'Employee' | 'Manager' | 'HRAdmin';
      /** @enum {string} */
      timeModel?:
        | 'Teilzeit'
        | 'Vollzeit'
        | 'Vertrauensarbeitszeit'
        | 'Gleitzeit';
      weeklyHours?: number;
      annualLeaveDays?: number;
      /** @example 2026-04-01 */
      startDate?: string;
      overtimeOpeningBalanceMinutes?: number;
      /**
       * @deprecated
       * @enum {string}
       */
      bundesland?:
        | 'BW'
        | 'BY'
        | 'BE'
        | 'BB'
        | 'HB'
        | 'HH'
        | 'HE'
        | 'MV'
        | 'NI'
        | 'NW'
        | 'RP'
        | 'SL'
        | 'SN'
        | 'ST'
        | 'SH'
        | 'TH';
      /**
       * @description Optional holiday preset. NONE makes no public-holiday assumptions; explicit holidayDates work in every country.
       * @default NONE
       * @enum {string}
       */
      holidayCalendar:
        | 'NONE'
        | 'DE-BW'
        | 'DE-BY'
        | 'DE-BE'
        | 'DE-BB'
        | 'DE-HB'
        | 'DE-HH'
        | 'DE-HE'
        | 'DE-MV'
        | 'DE-NI'
        | 'DE-NW'
        | 'DE-RP'
        | 'DE-SL'
        | 'DE-SN'
        | 'DE-ST'
        | 'DE-SH'
        | 'DE-TH';
      /**
       * @description Explicit non-working dates in YYYY-MM-DD format; supplement the selected preset.
       * @example [
       *       "2026-07-01"
       *     ]
       */
      holidayDates?: string[];
      /** @description Allow one self-approved fixed-duration block on a configured working day. */
      allowDailyBlockBooking?: boolean;
      /** Format: uuid */
      managerId?: Record<string, never> | null;
      /** Format: uuid */
      workScheduleId?: Record<string, never> | null;
      isActive?: boolean;
    };
    SetPasswordDto: {
      password: string;
    };
    BreakRuleDto: {
      /** @description Inclusive attendance threshold in minutes. */
      afterMinutes: number;
      /** @description Total deduction in minutes; must not exceed afterMinutes. */
      breakMinutes: number;
    };
    CoreTimeWindowDto: {
      /** @example Vormittag */
      label?: Record<string, never> | null;
      /** @example 10:00 */
      start: string;
      /** @example 11:00 */
      end: string;
      /** @description Bitmask: Mon=1, Tue=2, Wed=4, Thu=8, Fri=16, Sat=32, Sun=64. Mo–Fr = 31. */
      weekdays: number;
    };
    UpsertWorkScheduleDto: {
      name: string;
      description?: Record<string, never> | null;
      /** @example 07:00 */
      frameStart: string;
      /** @example 23:00 */
      frameEnd: string;
      /** @default false */
      isDefault: boolean;
      /**
       * @description Working-day bitmask. Mon=1, Tue=2, …, Sun=64. Mo–Fr = 31, Mo–Sa = 63.
       * @default 31
       */
      workingDays: number;
      /**
       * @description Automatic break deductions. Empty means none. The largest matching total applies; not a legal compliance guarantee. Omission on update preserves the policy.
       * @default []
       */
      breakRules: components['schemas']['BreakRuleDto'][];
      coreTimes: components['schemas']['CoreTimeWindowDto'][];
    };
    AssignToEmployeeDto: {
      /** Format: uuid */
      employeeId: string;
    };
    BulkAssignDto: {
      /** @enum {string} */
      timeModel:
        | 'Teilzeit'
        | 'Vollzeit'
        | 'Vertrauensarbeitszeit'
        | 'Gleitzeit';
      /** @default false */
      overrideExisting: boolean;
    };
    UpsertProjectDto: {
      /** @example PRJ-001 */
      code: string;
      name: string;
      description?: Record<string, never> | null;
      /** @default true */
      isActive: boolean;
      planHours?: Record<string, never> | null;
    };
    UpsertServiceOrderDto: {
      /** @example SA-2026-001 */
      orderNo: string;
      title: string;
      /** @default true */
      isActive: boolean;
      planHours?: Record<string, never> | null;
    };
    WorkingTimeReportEmployeeDto: {
      /** Format: uuid */
      id: string;
      firstName: string;
      lastName: string;
    };
    WorkingTimeReportLocationDto: {
      label: string | null;
      latitude: number | null;
      longitude: number | null;
      accuracyMeters: number | null;
    };
    WorkingTimeReportRowDto: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      employeeId: string;
      employeeName: string;
      /** Format: date */
      date: string;
      /** Format: date-time */
      clockIn: string;
      /** Format: date-time */
      clockOut: string;
      /** @enum {string} */
      status: 'Open' | 'Pending' | 'Approved';
      grossMinutes: number;
      breakMinutes: number;
      netMinutes: number;
      clockInLocation?:
        | components['schemas']['WorkingTimeReportLocationDto']
        | null;
      clockOutLocation?:
        | components['schemas']['WorkingTimeReportLocationDto']
        | null;
    };
    WorkingTimeReportTotalsDto: {
      grossMinutes: number;
      breakMinutes: number;
      netMinutes: number;
    };
    WorkingTimeReportDto: {
      /** Format: date */
      from: string;
      /** Format: date */
      to: string;
      rows: components['schemas']['WorkingTimeReportRowDto'][];
      totals: components['schemas']['WorkingTimeReportTotalsDto'];
    };
    ClockInDto: {
      /**
       * Format: uuid
       * @deprecated
       * @description Ignored. The employee identity is always taken from the JWT.
       */
      employeeId?: string;
      latitude?: number | null;
      longitude?: number | null;
      accuracyMeters?: number | null;
      /** Format: uuid */
      projectId?: string | null;
      /** Format: uuid */
      serviceOrderId?: string | null;
      activity?: string | null;
    };
    ClockOutDto: {
      /**
       * Format: uuid
       * @deprecated
       * @description Ignored. The employee identity is always taken from the JWT.
       */
      employeeId?: string;
      latitude?: number | null;
      longitude?: number | null;
      accuracyMeters?: number | null;
    };
    DailyBlockOptionDto: {
      enabled: boolean;
      /** @description Contractual net working minutes for one configured workday. */
      dailyNetMinutes: number;
      /** @description Attendance minutes including the configured automatic break deduction. */
      grossMinutes: number;
      breakMinutes: number;
      workdayCount: number;
    };
    CreateDailyBlockDto: {
      /** @example 2026-08-13 */
      date: string;
      /** @example 08:00 */
      start: string;
      /** Format: uuid */
      projectId?: string | null;
      /** Format: uuid */
      serviceOrderId?: string | null;
      activity?: string | null;
    };
    BookProjectRangeDto: {
      /** Format: uuid */
      employeeId: string;
      /** Format: date-time */
      from: string;
      /** Format: date-time */
      to: string;
      /** Format: uuid */
      projectId: string;
      /** Format: uuid */
      serviceOrderId?: string | null;
      activity?: string | null;
    };
    UpdateTimeEntryDto: {
      /** Format: uuid */
      projectId?: string | null;
      /** Format: uuid */
      serviceOrderId?: string | null;
      activity?: string | null;
    };
    SplitTimeEntryDto: {
      /** Format: date-time */
      at: string;
      /** Format: uuid */
      projectId?: string | null;
      /** Format: uuid */
      serviceOrderId?: string | null;
      activity?: string | null;
    };
    SupportPromptDto: {
      /** Format: date-time */
      shownAt?: string | null;
    };
    PairTerminalDto: {
      /** @example ABC23-DEFG4 */
      pairingCode: string;
      /** @example iPad Empfang */
      deviceName?: string;
    };
    KioskTerminalDto: {
      /** Format: uuid */
      id: string;
      name: string;
      displayText: string;
      locationLabel: string;
      logoUrl?: string | null;
      timeZone: string;
    };
    PairedTerminalDto: {
      /** @description Returned once. Persist securely in the kiosk browser. */
      deviceToken: string;
      terminal: components['schemas']['KioskTerminalDto'];
    };
    TerminalChallengeDto: {
      /** @description Opaque value to encode into the displayed QR code. */
      payload: string;
      /** Format: date-time */
      expiresAt: string;
      refreshAfterSeconds: number;
    };
    KioskStateDto: {
      terminal: components['schemas']['KioskTerminalDto'];
      challenge: components['schemas']['TerminalChallengeDto'];
      /** Format: date-time */
      serverTime: string;
    };
    ScanTerminalDto: {
      /** @description Opaque QR payload emitted by the kiosk. */
      qrPayload: string;
      /** @enum {string} */
      action?: 'clock-in' | 'clock-out';
      latitude?: number;
      longitude?: number;
      accuracyMeters?: number;
      /**
       * Format: date-time
       * @description Timestamp reported by the fresh browser geolocation reading.
       */
      positionTimestamp?: string;
    };
    TimeSummaryDto: {
      grossMinutes: number;
      breakMinutes: number;
      netMinutes: number;
    };
    TimeEntryDto: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      employeeId: string;
      /** Format: date-time */
      clockIn: string;
      /** Format: date-time */
      clockOut: string | null;
      /** @enum {string} */
      source: 'Manual' | 'Pwa' | 'Terminal' | 'Erp' | 'DailyBlock';
      /** @enum {string} */
      status: 'Open' | 'Pending' | 'Approved' | 'Rejected';
      requiresApproval: boolean;
      latitude: number | null;
      longitude: number | null;
      accuracyMeters: number | null;
      terminalDistanceMeters: number | null;
      /** @description Terminal geofence radius that was valid when clock-in was accepted. */
      terminalRadiusMeters: number | null;
      /** @description Terminal maximum GPS accuracy that was valid when clock-in was accepted. */
      terminalMaxAccuracyMeters: number | null;
      /** Format: date-time */
      positionTimestamp: string | null;
      clockOutLatitude: number | null;
      clockOutLongitude: number | null;
      clockOutAccuracyMeters: number | null;
      clockOutTerminalDistanceMeters: number | null;
      /** @description Terminal geofence radius that was valid when clock-out was accepted. */
      clockOutTerminalRadiusMeters: number | null;
      /** @description Terminal maximum GPS accuracy that was valid when clock-out was accepted. */
      clockOutTerminalMaxAccuracyMeters: number | null;
      /** Format: date-time */
      clockOutPositionTimestamp: string | null;
      /** Format: uuid */
      terminalId: string | null;
      /** Format: uuid */
      clockOutTerminalId: string | null;
      /** Format: uuid */
      clockInChallengeId: string | null;
      /** Format: uuid */
      clockOutChallengeId: string | null;
      /** Format: uuid */
      projectId: string | null;
      projectCode: string | null;
      projectName: string | null;
      /** Format: uuid */
      serviceOrderId: string | null;
      serviceOrderNo: string | null;
      serviceOrderTitle: string | null;
      activity: string | null;
      summary: components['schemas']['TimeSummaryDto'] | null;
    };
    ScanTerminalResultDto: {
      /** @enum {string} */
      action: 'clock-in' | 'clock-out';
      entry: components['schemas']['TimeEntryDto'];
      distanceMeters?: number | null;
    };
    TerminalDeviceDto: {
      /** Format: uuid */
      id: string;
      name?: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      lastSeenAt?: string | null;
      /** Format: date-time */
      revokedAt?: string | null;
    };
    TerminalDto: {
      /** Format: uuid */
      id: string;
      name: string;
      displayText: string;
      locationLabel: string;
      logoUrl?: string | null;
      enforceGeofence: boolean;
      latitude?: number | null;
      longitude?: number | null;
      radiusMeters?: number | null;
      maxAccuracyMeters?: number | null;
      timeZone: string;
      isActive: boolean;
      isPaired: boolean;
      deviceCount: number;
      /** Format: date-time */
      activatedAt?: string | null;
      /** Format: date-time */
      lastSeenAt?: string | null;
      devices: components['schemas']['TerminalDeviceDto'][];
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    CreateTerminalDto: {
      /** @example Haupteingang */
      name: string;
      /** @example Zum Ein- oder Ausstempeln QR-Code scannen */
      displayText: string;
      /** @example Büro Würzburg – Empfang */
      locationLabel: string;
      /** @description Same-origin path or a PNG/JPEG/WebP data URL (maximum 60 KiB decoded). */
      logoUrl?: string | null;
      /**
       * @description Require a fresh employee position inside the configured geofence.
       * @default true
       */
      enforceGeofence: boolean;
      /**
       * @description Required unless enforceGeofence is false.
       * @example 49.7913
       */
      latitude?: number | null;
      /**
       * @description Required unless enforceGeofence is false.
       * @example 9.9534
       */
      longitude?: number | null;
      /** @default 100 */
      radiusMeters: number | null;
      /** @default 100 */
      maxAccuracyMeters: number | null;
      /** @default UTC */
      timeZone: string;
      /** @default false */
      isActive: boolean;
    };
    UpdateTerminalDto: {
      /** @example Haupteingang */
      name?: string;
      /** @example Zum Ein- oder Ausstempeln QR-Code scannen */
      displayText?: string;
      /** @example Büro Würzburg – Empfang */
      locationLabel?: string;
      /** @description Same-origin path or a PNG/JPEG/WebP data URL (maximum 60 KiB decoded). */
      logoUrl?: string | null;
      /**
       * @description Require a fresh employee position inside the configured geofence.
       * @default true
       */
      enforceGeofence: boolean;
      /**
       * @description Required unless enforceGeofence is false.
       * @example 49.7913
       */
      latitude?: number | null;
      /**
       * @description Required unless enforceGeofence is false.
       * @example 9.9534
       */
      longitude?: number | null;
      /** @default 100 */
      radiusMeters: number | null;
      /** @default 100 */
      maxAccuracyMeters: number | null;
      /** @default UTC */
      timeZone: string;
      /** @default false */
      isActive: boolean;
    };
    PairingCodeDto: {
      /** @example ABC23-DEFG4 */
      pairingCode: string;
      /** @example /kiosk?pairing=ABC23-DEFG4 */
      pairingUrl: string;
      /** Format: date-time */
      expiresAt: string;
    };
    UpsertLeaveAllowanceDto: {
      /** @example 30 */
      baseDays: number;
      /** @example 0 */
      carryOverDays: number;
      /** Format: date */
      carryOverExpiresOn?: Record<string, never> | null;
      /**
       * @description Signed adjustment days (e.g. half-year entry pro-rata).
       * @example 0
       */
      adjustmentDays: number;
      adjustmentReason?: Record<string, never> | null;
    };
    CreateRequestDto: {
      /** Format: uuid */
      employeeId: string;
      /** @enum {string} */
      type: 'Vacation' | 'HomeOffice' | 'SpecialLeave' | 'TimeAdjustment';
      /**
       * Format: date-time
       * @example 2026-08-03T00:00:00.000Z
       */
      from: string;
      /**
       * Format: date-time
       * @example 2026-08-07T00:00:00.000Z
       */
      to: string;
      reason?: Record<string, never> | null;
    };
    CreateVacationDto: {
      /** Format: uuid */
      employeeId: string;
      /** Format: date-time */
      from: string;
      /** Format: date-time */
      to: string;
      /** Format: uuid */
      substituteId?: Record<string, never> | null;
      reason?: Record<string, never> | null;
      /**
       * @description Take the first day as a half-day
       * @default false
       */
      halfDayStart: boolean;
      /**
       * @description Take the last day as a half-day
       * @default false
       */
      halfDayEnd: boolean;
    };
    TransitionDto: {
      /** Format: uuid */
      actorId: string;
      note?: Record<string, never> | null;
    };
    ManagerApproveDto: {
      /** Format: uuid */
      actorId: string;
      note?: Record<string, never> | null;
      /** @default false */
      requiresHrConfirmation: boolean;
    };
    TransitionWithRequiredNoteDto: {
      /** Format: uuid */
      actorId: string;
      note: string;
    };
    BulkApproveDto: {
      /** Format: uuid */
      actorId: string;
      ids: string[];
      note?: Record<string, never> | null;
      /** @default false */
      requiresHrConfirmation: boolean;
    };
    BulkRejectDto: {
      /** Format: uuid */
      actorId: string;
      ids: string[];
      note: string;
    };
    CreateAbsenceDto: {
      /** Format: uuid */
      employeeId: string;
      /**
       * @default Sickness
       * @enum {string}
       */
      kind: 'Sickness' | 'Training' | 'Flextime';
      /** Format: date-time */
      from: string;
      /** Format: date-time */
      to: string;
      /**
       * @description Sickness only: ärztliches Attest vorgelegt.
       * @default false
       */
      certified: boolean;
      note?: Record<string, never> | null;
    };
    UpdateAbsenceDto: {
      /** Format: date-time */
      from?: string;
      /** Format: date-time */
      to?: string;
      certified?: boolean;
      note?: Record<string, never> | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  AuthController_login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_refresh: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RefreshDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_me: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_updatePreferences: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdatePreferencesDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  HealthController_check: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HealthResponseDto'];
        };
      };
    };
  };
  EmployeesController_list: {
    parameters: {
      query: {
        includeInactive: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  EmployeesController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateEmployeeDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  EmployeesController_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  EmployeesController_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateEmployeeDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  EmployeesController_deactivate: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  EmployeesController_setPassword: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SetPasswordDto'];
      };
    };
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  EmployeesController_reactivate: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  WorkSchedulesController_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  WorkSchedulesController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpsertWorkScheduleDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  WorkSchedulesController_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  WorkSchedulesController_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpsertWorkScheduleDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  WorkSchedulesController_remove: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  WorkSchedulesController_assign: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AssignToEmployeeDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  WorkSchedulesController_bulkAssign: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['BulkAssignDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ProjectsController_list: {
    parameters: {
      query: {
        includeInactive: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ProjectsController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpsertProjectDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ProjectsController_listAssignments: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ProjectsController_listBookable: {
    parameters: {
      query: {
        employeeId: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ProjectsController_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ProjectsController_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpsertProjectDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ProjectsController_remove: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ProjectsController_report: {
    parameters: {
      query: {
        from: string;
        to: string;
      };
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ProjectsController_createServiceOrder: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpsertServiceOrderDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ProjectsController_updateServiceOrder: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
        orderId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpsertServiceOrderDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ProjectsController_removeServiceOrder: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
        orderId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ProjectsController_assign: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
        employeeId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ProjectsController_unassign: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
        employeeId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ReportsController_workingTimeEmployees: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['WorkingTimeReportEmployeeDto'][];
        };
      };
    };
  };
  ReportsController_workingTimes: {
    parameters: {
      query: {
        from: string;
        to: string;
        employeeId?: string;
        includeLocations?: boolean;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['WorkingTimeReportDto'];
        };
      };
    };
  };
  TimeEntriesController_list: {
    parameters: {
      query: {
        employeeId: string;
        from: string;
        to: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TimeEntriesController_clockIn: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ClockInDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TimeEntriesController_clockOut: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ClockOutDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TimeEntriesController_dailyBlockOption: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DailyBlockOptionDto'];
        };
      };
    };
  };
  TimeEntriesController_dailyBlock: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateDailyBlockDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TimeEntriesController_bookProject: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['BookProjectRangeDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TimeEntriesController_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateTimeEntryDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TimeEntriesController_split: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SplitTimeEntryDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TerminalsController_supportPrompt: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SupportPromptDto'];
        };
      };
    };
  };
  TerminalsController_dismissSupportPrompt: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SupportPromptDto'];
        };
      };
    };
  };
  TerminalsController_pair: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['PairTerminalDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PairedTerminalDto'];
        };
      };
    };
  };
  TerminalsController_kiosk: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['KioskStateDto'];
        };
      };
    };
  };
  TerminalsController_scan: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ScanTerminalDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ScanTerminalResultDto'];
        };
      };
    };
  };
  TerminalsController_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TerminalDto'][];
        };
      };
    };
  };
  TerminalsController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateTerminalDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TerminalDto'];
        };
      };
    };
  };
  TerminalsController_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TerminalDto'];
        };
      };
    };
  };
  TerminalsController_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateTerminalDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TerminalDto'];
        };
      };
    };
  };
  TerminalsController_deactivate: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TerminalDto'];
        };
      };
    };
  };
  TerminalsController_deletePermanently: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Permanently deletes the terminal and kiosk-only data. Historical time entries remain. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TerminalsController_createPairing: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PairingCodeDto'];
        };
      };
    };
  };
  TerminalsController_revokeDevice: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
        deviceId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TerminalDto'];
        };
      };
    };
  };
  LeaveAllowancesController_list: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        employeeId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  LeaveAllowancesController_upsert: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        employeeId: string;
        year: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpsertLeaveAllowanceDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  LeaveAllowancesAdminController_expireCarryOvers: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  CronCarryOverController_expireCarryOvers: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AccountsController_account: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        employeeId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AccountsController_vacationBalance: {
    parameters: {
      query: {
        year: number;
      };
      header?: never;
      path: {
        employeeId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  RequestsController_list: {
    parameters: {
      query: {
        employeeId: string;
        status: string;
        workflowState: string;
        approverId: string;
        currentApproverId: string;
        substituteId: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  RequestsController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateRequestDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  RequestsController_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  RequestsController_events: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  RequestsController_createVacation: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateVacationDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  RequestsController_approve: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['TransitionDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  RequestsController_reject: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['TransitionDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  RequestsController_managerApprove: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ManagerApproveDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  RequestsController_managerReject: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['TransitionDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  RequestsController_hrConfirm: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['TransitionDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  RequestsController_hrReject: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['TransitionWithRequiredNoteDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  RequestsController_substituteAccept: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['TransitionDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  RequestsController_substituteDecline: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['TransitionWithRequiredNoteDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  RequestsController_returnForRevision: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['TransitionWithRequiredNoteDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  RequestsController_cancel: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['TransitionDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  RequestsController_bulkApprove: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['BulkApproveDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  RequestsController_bulkReject: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['BulkRejectDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AbsencesController_list: {
    parameters: {
      query: {
        employeeId: string;
        from: string;
        to: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AbsencesController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateAbsenceDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AbsencesController_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateAbsenceDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AbsencesController_remove: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AttachmentsController_list: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        requestId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AttachmentsController_upload: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        requestId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'multipart/form-data': {
          /** Format: binary */
          file: string;
        };
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AttachmentsController_download: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AttachmentsController_remove: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ViolationsController_list: {
    parameters: {
      query: {
        employeeId: string;
        from: string;
        to: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ErpExportController_list: {
    parameters: {
      query: {
        from: string;
        to: string;
        page: number;
        pageSize: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
